### ISSUE TITLE
PandaReach, PandaPickAndPlace, assign @benthebear93

### ISSUE THREAD

**Issue by CUN-bjy** [ropiens/project-sandwich-man#4]

**Comment by benthebear93** [comment]
Reacher trained by SAC-HER
![reacher_sac_her](https://user-images.githubusercontent.com/34788458/130316681-b0fabf38-a1fe-47ec-8f06-e5063b4a3cfb.gif)
![sac-her-panda-reach](https://user-images.githubusercontent.com/34788458/130316687-a3447341-a021-4aad-8974-81a120089458.PNG)
PickAndPlace trained by SAC-HER
![pp_sac_her](https://user-images.githubusercontent.com/34788458/130316709-a5dd0ad1-fd12-40ea-a25c-55ba9fce9724.gif)
![sac-her-panda-pp](https://user-images.githubusercontent.com/34788458/130316713-6e874868-89cc-4d56-b7fe-3fcd56b018f5.PNG)
(poor gif need to be improved. Wasn't able to "load" the model since i forgot to save Replay buffer)

**Comment by CUN-bjy** [comment]
give some hyperparameters pls..
